### ISSUE TITLE
purrr?

### ISSUE THREAD

**Issue by DanOvando** [eco-data-science/eco-data-science-old-site#17]
Has anyone started playing with the `purrr` package? It looks useful, but feel like I could use some examples beyond the documentation to really get the hang of it

**Comment by grantmcdermott** [comment]
Hey @DanOvando, I've used it a bit. Mostly for splitting dataframes up by groups and then mapping some function over them before extracting the key results. I think that's pretty similar to the example documentation, but happy to go through my code if you want...
