### ISSUE TITLE
rstudio::conf debrief tomorrow!

### ISSUE THREAD

**Issue by jamiecmontgomery** [eco-data-science/eco-data-science-old-site#32]
Juan Mayorga (@juanmayorgahenao) was lucky enough to travel to Orlando and attend the first ever [rstudio conference](https://www.rstudio.com/conference/). He'll be giving an update about what he learned and what's new in the world of RStudio. Don't miss out! 

Where: Bren 1424
When: Jan 27th at 10:00 am

Notes from Juan:

So that you can follow along during the workshop please make sure you have the latest R and RStudio versions. To do this, just type `devtools::dr_devtools()` in your console! (pro tip courtesy of Hadley himself)

Some packages we will we be working with are: `tidyverse`, `broom`, `modelr`,  `purrr`, `shiny` so please check you have them installed in your machines.

**Comment by zenrabbit** [comment]
was this today?

**Comment by jamiecmontgomery** [comment]
Sorry left off the date - it's tomorrow the 27th!

**Comment by zenrabbit** [comment]
Super. Be cool to get the precis!

**Comment by reblake** [comment]
Can this presentation be recorded?  I can't attend because I'm hosting a writing retreat tomorrow, but am interested in this!

**Comment by spfitzgerald** [comment]
I very strongly second that motion if possible!  I have a weekly meeting on
Fridays from 10-11 AM and am really sad I'm missing this tomorrow :(

**Comment by sparrow925** [comment]
Another vote for reschedule! I'm out of town till Monday.

**Comment by jamiecmontgomery** [comment]
This session is a previously arranged presentation by Juan to the Sustainable Fisheries Group and they are graciously opening it up to the EcoDataScience community. So we aren't able to reschedule for another day. I think it will run from 10 - 12 (right @juanmayorgahenao?) so @spfitzgerald come by after your meeting!

I'm not sure if we'll be able to get it recorded, the only option I can think of is getting people to skype in as we've done before and doing a screen share? Or possibly set up a zoom event, which admittedly I've never done....

**Comment by spfitzgerald** [comment]
OK! Thanks!

**Comment by sparrow925** [comment]
Ah OK! Thanks for the info! I just used zoom for the first time this week
to record a meeting, it worked pretty smoothly. Let us know if it ends up
being something shareable!

**Comment by juanmayorgahenao** [comment]
Yes @jafflerbach, the workshop will go until 12.  @spfitzgerald you'll be able the join us for the second half.

**Comment by juanmayorgahenao** [comment]
Thanks everyone for attending the workshop today. 

You can download materials from here: https://ucsb.box.com/s/g5i6eimzdk5mrc3f4rof95pgnwsuahzo and you can access all the conferences slides from https://github.com/kbroman/RStudioConf2017Slides

Thanks

Juan

**Comment by jamiecmontgomery** [comment]
Thanks so much for the great overview Juan and Alex. Is it possible to get the materials on github? I can then link to them for those outside of UCSB that may not be able to access the box account.

**Comment by juanmayorgahenao** [comment]
Hi @jafflerbach, here is a dropbox link that should work for everyone: https://www.dropbox.com/s/hjm3yc06vdgia5p/Rstudio_conf_debrief.zip?dl=0 

I don't think I have the access to this organization to create a repo :)

**Comment by jamiecmontgomery** [comment]
Thanks! If you do want to create a repo, I suggest doing a personal repo under your github name and then I can fork it to the eco-data-science organization.
