### ISSUE TITLE
Poll for EcoDataScience sessions 2017-2018

### ISSUE THREAD

**Issue by jamiecmontgomery** [eco-data-science/eco-data-science-old-site#40]
Hi ecodatascience! 

First, apologies for cross-posting with our Google Group but not everyone in ecodatascience is on GitHub.

This year we are strongly considering hosting monthly ecodatascience sessions at the [UCSB Library Collaboratory](https://www.library.ucsb.edu/interdisciplinary-research-collaboratory) space. If you haven't been, the Collaboratory is a great space in the library with fantastic computing resources. And as a bonus, they have funds to provide food during our sessions!

We'd like to select a single day and time each month for our sessions. For example the third Monday each month from 11 - 1. Please fill out the survey to let us know your preferred date and time for monthly sessions. If there is ever a desire to lead a session on something that might not fit into the monthly schedule we can still find a way to set something up. There is also a space to identify what sessions you would like to see ecodatascience host this year. 

survey: [https://goo.gl/forms/BiWLZK1jS8gActCm2](https://goo.gl/forms/BiWLZK1jS8gActCm2)

**Comment by jcvdav** [comment]
Hi @jafflerbach,

Thanks for organizing this. No sure if its just me, but the  survey seems to be blocked. Just to make sure we can all answer it.

![image](https://user-images.githubusercontent.com/11950459/29797751-d159cf3c-8c0d-11e7-8434-29eba33e754e.png)

Tahanks!

**Comment by jamiecmontgomery** [comment]
Thanks - it was accidentally locked to NCEAS emails only. Should be fixed now but let me know if there are other issues

**Comment by jcvdav** [comment]
It works now! Thanks!
