### ISSUE TITLE
First EcoDataScience session on October 4th - poll for what to do!?

### ISSUE THREAD

**Issue by jamiecmontgomery** [eco-data-science/eco-data-science-old-site#42]
Our first ecodatascience session is set for **October 4th, 2017 from 11:30 - 1pm** in the UCSB collaboratory. I will also work on getting a remote connection but strongly suggest folks on campus come to this inaugural session for the 2017-2018 school year! 

**BONUS: LUNCH WILL BE SERVED** 👨‍💻  :pouch: 👩‍💻 🍔 

To determine what this first session should be I'm going to test out this [integration of polls in github issues](https://github.com/apex/gh-polls).

Please click on what you'd like to see for the kickoff session. We can use the results to help determine the schedule for the rest of the year as well. And also comment with other ideas or your offers to teach 😄 :

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Spatial%20Analysis%20in%20R)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Spatial%20Analysis%20in%20R/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/intro%20to%20the%20tidyverse%20(dplyr%20%2B%20tidyr))](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/intro%20to%20the%20tidyverse%20(dplyr%20%2B%20tidyr)/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/data%20visualization%20with%20ggplot2%20and%20more)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/data%20visualization%20with%20ggplot2%20and%20more/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/RMarkdown)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/RMarkdown/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/EcoDataScience%20show%20and%20tell%20(4-6%20people%20demo%20cool%20stuff%20they've%20been%20working%20on))](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/EcoDataScience%20show%20and%20tell%20(4-6%20people%20demo%20cool%20stuff%20they've%20been%20working%20on)/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Intro%20to%20Git%20and%20GitHub)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Intro%20to%20Git%20and%20GitHub/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Advanced%20Git%20and%20GitHub%20(merging%2C%20branches%2C%20etc.))](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Advanced%20Git%20and%20GitHub%20(merging%2C%20branches%2C%20etc.)/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Shiny)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BSF3XCNRYA9CPAGTV3ZN6H6T/Shiny/vote)

**Comment by jamiecmontgomery** [comment]
ps you'll have to look at the [poll in the GitHub issue itself](https://github.com/eco-data-science/eco-data-science.github.io/issues/42), it doesn't render in email

**Comment by zenrabbit** [comment]
wow, I love the poll function! even voting with eco-data-science is a learning process! Thanks :)

**Comment by jamiecmontgomery** [comment]
Spatial analysis it is! We can do RMarkdown in November.
